services:
  db:
    build: .
    container_name: inventario_db
    ports:
      - "3308:3306"  # Cambia el puerto 3306 a 3307
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventario
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: